title: Test Custom Template
branchName: s
commitMessage: |
  {{ jira_ids }} This pull request is from Snyk {{ jira_ids }}
description: |
  **Tickets**
  {{ #jira_ids }}
  - Fixes {{ . }}
  {{ /jira_ids }}

  To find more details, see the Snyk project [{{ snyk_project_name }}]({{ snyk_project_url }})
