title: TEST CUSTOM PR TEMPLATE
branchName: TEST BRANCH
commitMessage: TEST COMMIT MESSAGE FOR JIRA TICKET: {{ jira_ids }}
description: THIS IS A TEST DESCRIPTION
  
  **Tickets**
  {{ jira_ids }}
  - Fixes {{ . }}
  {{ /jira_ids }}
  
  To find more details, see the Snyk project [{{ snyk_project_name }}]({{ snyk_project_url }})
